### ISSUE TITLE
Doesn't work with Tuinity 1.16.5

### ISSUE THREAD

**Issue by Acult** [FN-FAL113/SfChunkInfo#8]
Issue:
The addon cannot run /shchunkinfo command, 

Error log: https://pastebin.com/45R1fTYK

Using Tuinity 1.16.5, Slimefun dev 1008, Sfchunkinfo dev 4.

**Comment by FN-FAL113** [comment]
Sorry for the late reply, will fix this in the next build

**Comment by FN-FAL113** [comment]
Tuinity is merged with Paper, I advise using paper if you can

**Comment by FN-FAL113** [comment]
Fixed in the new build :)
